services:
  app:
    container_name: library-prod
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    env_file:
      - .env.prod
    restart: always
    command: flask run -h 0.0.0.0
  db_prod:
    container_name: library-db-prod
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: library-db-prod
    restart: always
    volumes:
      - db_data_prod:/var/lib/postgres/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  db_data_prod:
