version: '3.8'

services:
  app: # On peut le renommer 'app_prod' si on veut
    container_name: library-prod
    build: .
    ports:
      - "5000:5000" # Le port de production
    volumes: [] # ON RETIRE LE VOLUME ! Le code est dans l'image.
    env_file:
      - .env.prod
    restart: always
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app # Commande de production
    depends_on:
      - db_prod

  db_prod:
    container_name: library-db-prod
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: library-db-prod
    volumes:
      - db_data_prod:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  db_data_prod: