services:
  db_dev:
    image: postgres:13.22-alpine3.21
    container_name: postgres_db_dev
    environment:
      POSTGRES_DB: library_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ultrasecret1
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  db_prod:
    image: postgres:13.22-alpine3.21
    container_name: postgres_db_prod
    environment:
      POSTGRES_DB: library_prod
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ultrasecret2
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
  postgres_data_prod: