version: '3.8'

services:
  library-dev:
    container_name: library-dev
    build: .
    ports:
      - "5000:5000" 
    volumes:
      - .:/app
    env_file:
      - .env.dev
    restart: always
    depends_on:
      - db_dev

  db_dev:
    container_name: library-db-dev
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: library-db-dev
    volumes:
      - db_data_dev:/var/lib/postgresql/data

volumes:
  db_data_dev: