[tool.ruff]
target-version = "py39"
line-length = 88

select = ["E", "F", "I", "B", "C90"]

[tool.ruff.format]
quote-style = "double"

[tool.ruff.per-file-ignores]
"app/**/__init__.py" = ["F401", "E402"]
