services:
  db:
    image: postgres:13
    container_name: flask_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ultrasecret1
      POSTGRES_DB: library_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: